conn_lc:in_fact conn:In_fact conn_POS:IN_NN xxx£
conn_lc:since conn:since conn_POS:IN with_prev_full:ever_since xxx£
conn_lc:but conn:But conn_POS:CC xxx£
conn_lc:when conn:when conn_POS:WRB with_prev_full:agency_when xxx£
conn_lc:and conn:and conn_POS:CC with_prev_full:france_and xxx£
conn_lc:when conn:when conn_POS:WRB with_prev_full:and_when xxx£
conn_lc:before conn:before conn_POS:IN with_prev_full:just_before xxx£
conn_lc:but conn:but conn_POS:CC with_prev_full:,_but xxx£
conn_lc:but conn:but conn_POS:CC with_prev_full:,_but xxx£
conn_lc:and conn:and conn_POS:CC with_prev_full:,_and xxx£
conn_lc:when conn:when conn_POS:WRB with_prev_full:only_when xxx£
conn_lc:but conn:but conn_POS:CC with_prev_full:,_but xxx£
